apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: osg-wn-gpu-prp-sdsc
  namespace: osggpus
  labels: 
    k8s-app: osg-wn-gpu
spec:
  template:
    metadata: 
      labels:
        k8s-app: osg-wn-gpu
    spec:
      containers:
      - name: osg-wn-gpu
        image: sfiligoi/prp-osg-pool:wn-gpu
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        resources:
           limits:
             nvidia.com/gpu: 1
             memory: 6Gi
           requests:
             nvidia.com/gpu: 1
             memory: 4Gi
             cpu: 1
        volumeMounts:
        - name: configpasswd
          mountPath: /var/lock/condor/pool_password
          subPath: pool_password
          readOnly: true
        - name: confighost
          mountPath: /etc/condor/config.d/50_condor_host.config
          subPath: 50_condor_host.config
          readOnly: true
        - name: configmem
          mountPath: /etc/condor/config.d/02_memory_limits.config
          subPath: 02_memory_limits.config
          readOnly: true
        - name: cvmfs-config-osg
          mountPath: /cvmfs/config-osg.opensciencegrid.org
          readOnly: true
        - name: cvmfs-oasis
          mountPath: /cvmfs/oasis.opensciencegrid.org
          readOnly: true
        - name: cvmfs-icecube
          mountPath: /cvmfs/icecube.opensciencegrid.org
          readOnly: true
        - name: cvmfs-stash
          mountPath: /cvmfs/stash.osgstorage.org
          readOnly: true
      volumes:
      - name: configpasswd
        secret:
          secretName: osg-wn-prp-sdsc-config
          items:
             - key: pool_password
               path: pool_password
          defaultMode: 256
      - name: confighost
        secret:
          secretName: osg-wn-prp-sdsc-config
          items:
             - key: 50_condor_host.config
               path: 50_condor_host.config
          defaultMode: 292
      - name: configmem
        secret:
          secretName: osg-wn-prp-sdsc-config
          items:
             - key: 02_memory_limits.config
               path: 02_memory_limits.config
          defaultMode: 292
      - name: cvmfs-config-osg
        persistentVolumeClaim:
          claimName: csi-cvmfs-pvc-config-osg
          readOnly: true
      - name: cvmfs-oasis
        persistentVolumeClaim:
          claimName: csi-cvmfs-pvc-oasis
          readOnly: true
      - name: cvmfs-icecube
        persistentVolumeClaim:
          claimName: csi-cvmfs-pvc-icecube
          readOnly: true
      - name: cvmfs-stash
        persistentVolumeClaim:
          claimName: csi-cvmfs-pvc-stash
          readOnly: true

