apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: osg-wn-cvmfs
  namespace: osggpus
spec:
  selector:
    matchLabels:
      role: osg-wn
  volumeMounts:
    - name: cvmfs-config-osg
      mountPath: /cvmfs/config-osg.opensciencegrid.org
      readOnly: true
    - name: cvmfs-oasis
      mountPath: /cvmfs/oasis.opensciencegrid.org
      readOnly: true
    - name: cvmfs-connect
      mountPath: /cvmfs/connect.opensciencegrid.org
      readOnly: true
    - name: cvmfs-icecube
      mountPath: /cvmfs/icecube.opensciencegrid.org
      readOnly: true
    - name: cvmfs-stash
      mountPath: /cvmfs/stash.osgstorage.org
      readOnly: true
  volumes:
    - name: cvmfs-config-osg
      persistentVolumeClaim:
        claimName: csi-cvmfs-pvc-config-osg
        readOnly: true
    - name: cvmfs-oasis
      persistentVolumeClaim:
        claimName: csi-cvmfs-pvc-oasis
        readOnly: true
    - name: cvmfs-connect
      persistentVolumeClaim:
        claimName: csi-cvmfs-pvc-connect
        readOnly: true
    - name: cvmfs-icecube
      persistentVolumeClaim:
        claimName: csi-cvmfs-pvc-icecube
        readOnly: true
    - name: cvmfs-stash
      persistentVolumeClaim:
        claimName: csi-cvmfs-pvc-stash
        readOnly: true

